- source/includes/_events.md
> Events resources

- source/includes/_attendee_type.md
> attendee type resources

- Gemfile
- Gemfile.lock
- source/includes/_attendees.md
- source/includes/_workshops.md
- source/index.html.md
> add workshop

- source/includes/_speakers.md
- source/index.html.md
Create Pull Request Speaker en Eventtia-Core-Dod
> Add speaker in eventtia-core-doc

- source/includes/_attendee_type.md
- source/includes/_attendees.md
- source/includes/_events.md
- source/includes/_fields.md
- source/includes/_pricing_tier.md
- source/includes/_speakers.md
- source/includes/_workshops.md
> fixes path parameters

- source/includes/_account_subscriptions.md
- source/includes/_attendee_type.md
- source/includes/_attendees.md
- source/includes/_commercial_plans.md
- source/includes/_events.md
- source/includes/_pricing_tier.md
- source/includes/_speakers.md
- source/includes/_workshops.md
- source/index.html.md
> Add subscription and plans

- source/includes/_registrations.md
- source/includes/_users.md
- source/index.html.md
> Users CRUD

- source/includes/_recovery_password.md
- source/index.html.md
> Add Recovery Password

- source/includes/_attendees.md
- source/includes/_introduction.md
- source/index.html.md
> attendees filter

- source/includes/_attendee_type.md
- source/includes/_events.md
- source/includes/_speakers.md
- source/includes/_users.md
- source/includes/_workshops.md
> Filter events

- source/includes/_activation.md
- source/includes/_attendee_type.md
- source/index.html.md
> available and activation endpoint

- source/includes/_events.md
- source/includes/_recovery_password.md
> minor fixes

- source/includes/_passwords.md
- source/includes/_users.md
- source/index.html.md
> password endpoint added

- source/includes/_passwords.md
- source/includes/_users.md
> update password endpoints

- source/includes/_permissions.md
- source/includes/_role_categories.md
- source/includes/_role_permissions.md
- source/includes/_roles.md
- source/includes/_users.md
- source/index.html.md
> Role and Permissions

- source/includes/_passwords.md
- source/index.html.md
> Reorder modules

- source/includes/_attendee_type.md
> Documentation form fields

- source/includes/_users.md
> Update user documentation

- source/includes/_attendee_types.md
- source/includes/_notifications.md
- source/index.html.md
> notification added

- source/includes/_orders.md
- source/index.html.md
> orders create added

- source/includes/_account_subscriptions.md
- source/includes/_activation.md
- source/includes/_attendee_types.md
- source/includes/_attendees.md
- source/includes/_commercial_plans.md
- source/includes/_events.md
- source/includes/_fields.md
- source/includes/_introduction.md
- source/includes/_notifications.md
- source/includes/_orders.md
- source/includes/_passwords.md
- source/includes/_permissions.md
- source/includes/_pricing_tier.md
- source/includes/_public_endpoints.md
- source/includes/_registrations.md
- source/includes/_role_categories.md
- source/includes/_role_permissions.md
- source/includes/_roles.md
- source/includes/_speakers.md
- source/includes/_users.md
- source/includes/_workshops.md
- source/index.html.md
> Public endpoints

- source/includes/_tickets.md
- source/index.html.md
> tickets added

- source/includes/_public_endpoints.md
- source/includes/_widget_settings.md
- source/includes/_workshops.md
- source/index.html.md
> widgets added

- source/includes/_public_endpoints.md
> endpoint auth public

- source/includes/_attendee_types.md
- source/includes/_fields.md
- source/includes/_notifications.md
- source/includes/_public_endpoints.md
- source/includes/_roles.md
- source/includes/_tickets.md
- source/includes/_users.md
> Various fixes

- source/includes/_public_endpoints.md
> attendees and tickets endpoints added

- source/includes/_roles.md
> users added to role

- source/includes/_role_categories.md
- source/includes/_users.md
> added role and users relationships

- source/includes/_events.md
> adde role category to events

- source/includes/_users.md
> added current-user and categories

- source/includes/_account_subscriptions.md
> Documentation of the payment method change

- lib/toc_data.rb
- source/includes/stats/account/_account_endpoints.md
- source/includes/stats/event/_event_endpoints.md
- source/includes/stats/role/_role_endpoints.md
- source/includes/stats/role_category/_role_category_endpoints.md
- source/index.html.md
- source/javascripts/all_nosearch.js
- source/javascripts/app/_search.js
- source/layouts/layout.erb
- source/stylesheets/screen.css.scss
> Stats Endpoints

- source/includes/_account_subscriptions.md
- source/includes/_activation.md
- source/includes/_attendee_types.md
- source/includes/_attendees.md
- source/includes/_commercial_plans.md
- source/includes/_events.md
- source/includes/_fields.md
- source/includes/_introduction.md
- source/includes/_notifications.md
- source/includes/_orders.md
- source/includes/_passwords.md
- source/includes/_permissions.md
- source/includes/_pricing_tier.md
- source/includes/_public_endpoints.md
- source/includes/_registrations.md
- source/includes/_role_categories.md
- source/includes/_role_permissions.md
- source/includes/_roles.md
- source/includes/_speakers.md
- source/includes/_tickets.md
- source/includes/_users.md
- source/includes/_widget_settings.md
- source/includes/_workshops.md
> new format for titles

- source/includes/_events.md
- source/includes/_notifications.md
> update docs taxes and notifications

- source/includes/_notifications.md
> Mass Notification Feature

- source/includes/_public_endpoints.md
> added order create attendee

- source/includes/_fields.md
> fix responses

- source/includes/_notifications.md
> tags notification added

- source/includes/_attendees.md
> checking and confirmed endpoints added

- source/includes/_attendees.md
>  fixes endpoint confirm

- source/includes/_attendee_types.md
- source/includes/_fields.md
- source/includes/_notifications.md
> Notification Documentation Update

- source/includes/_attendee_types.md
> Endpoint Entity Notification Feature

- source/includes/_attendees.md
- source/includes/stats/event/_event_endpoints.md
> Stats timeline

- source/includes/_events.md
> timezone added

- source/includes/_account_subscriptions.md
- source/includes/_orders.md
- source/includes/_registrations.md
> Base Url Feature

- source/includes/_attendees.md
> send email

- source/includes/_events.md
> fix events endpoints
